### ISSUE TITLE
Question: Ignore `require` dependencies

### ISSUE THREAD

**Issue by piuccio** [dependents/node-detective-amd#13]
Is there a way, or would you consider adding an option to ignore `require`d dependencies:

```js
define(['a'], function (a) {
   require(['b'], function (b) {});
})
```

I'm only interested in `a`. Or even better I'd like to know that `a` is a direct dependency while `b` is a ??? dependency (don't know how to call it).

The reason being webpack and r.js handle these dependencies differently. When bundling these two tools will keep `b` out of the bundle. So I'd like to be able to instruct `node-detective-amd` to only return what these tools consider as a dependency.

Hope it makes sense

**Comment by mrjoelkemp** [comment]
Hey @piuccio! Thanks for asking the question!

Out of curiosity, for what purpose are you using detective-amd?

> while b is a ??? dependency (don't know how to call it).

The inner require would be a "lazy-loaded" dependency. 

I'm definitely open to having a flag that allows you to omit lazy-loaded dependencies. However, there's a [form of defining an AMD module](http://requirejs.org/docs/api.html#cjsmodule) that doesn't consider inner requires as lazy. We'd have to guard against that being omitted when the flag is on.

Would you be open to creating a PR with the changes and tests?

**Comment by piuccio** [comment]
Hi, I'll try to explain this the best I can. 

I have a big application written in requirejs, it's composed of 3 main modules which lazy load other bootstrap modules. 
All this is done with grunt and requirejs plugins. 

When bundling the bootstrap modules, I can tell requirejs to generate a bundle including all direct dependencies excluding anything that's already a direct dependency of the main modules. 

I'm trying to migrate this setup to rollup without rewriting my files. I wrote rollup-plugin-amd that converts amd to es6 at build time, but now I need to mark some dependencies as external because are provided by the main modules. 
I was trying to use madge, which uses node-detective to get a list of dependencies, but that includes lazy loaded files, in other words everything. 

I don't have much time to properly do a PR, especially to cover the edge case, but if it's trivial I'll give it a go

**Comment by mrjoelkemp** [comment]
@piuccio I added a `skipLazyLoaded` option to a [new second argument](https://github.com/dependents/node-detective-amd/blob/56fb9e54dad642893215f622b0bdb0265263703f/test/index.js#L138) that skips inner requires (except in the REM form).

I published a minor release with the changes. Let me know if that suits your needs.

Cheers! Thanks again for the request and for using the library.
